Работа с DOM. Загрузка документа
js-tasks-ru/js-20201030_chexov34 pull request #6
Opened 2020-11-15 19:24 UTC by chex0v

Класс SortableTable

2020-11-15 19:31 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-15 19:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-15 21:05 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  constructor(message, { duration = 1000, type = "success", header = 'Success'} = {}) {
good 👍

2020-11-15 21:06 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static createElementFromString(string) {
нет необходимости выносить эту логику в статическое свойство класса. Статические свойства необходимы для того чтобы работать без инстанциирования класса.

2020-11-15 21:06 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show(root = null) {
а почему бы не задать `root = document.body`?

2020-11-15 21:07 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    } else {
тогда вот от этой `if...else` конструкции можно избавиться

2020-11-15 21:07 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    NotificationMessage._timer = setTimeout(
почему `_time` - это статическое свойство?

2020-11-15 21:08 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    NotificationMessage._timer = setTimeout(
почему имена некоторых свойств класса начинаются с символа `_`?

2020-11-15 21:13 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  subElements = {
нет необходимости хардкодить свойства в данном объекте. Мы хотим собрать этот объект динамически опираясь на дата атрибуты в тимплейте. Поменяется тимлейт - прийдется менять поля в данном объекте - а это нехорошо

2020-11-15 21:15 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  sortStrings(arr, key, param = "asc") {
а почему бы не объединить эти две функции сортировки в одну? Ведь по факту они делают одно и тоже просто с разными типами данных... А проверку в `switch...case` как раз будет удобно орнанизовать по типу данных...

2020-11-15 21:16 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  static createElementFromString(string) {
уже второй раз вижу в работах такой метод, поэтому вопрос: "Почему этот мтеод статический?"

2020-11-15 21:16 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    return div.firstChild;
В чем разница межу `firstChild` и `firstElementChild`?

2020-11-15 21:17 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  getClassString(arr) {
попытка хороша, но конкретно в данной компоненте эта функция решает какую проблему?

2020-11-15 21:18 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +      <div
может не следует перегружать данный метод еще и шаблонной строкой? может следует вынести ее в отдельный метод?

2020-11-15 21:20 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    return this.header.map((h) => {
`h` - это плохое имя аргумента, слишком короткое.

2020-11-15 21:23 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    this.subElements.table = SortableTable.createElementFromString(
`subElements` мы должны автоматически собрать из элементов, путем выборки и обхода в цикле элементов внутри нашего главного элемента-обертки `this.element` - посмотрите пожалуйста на решение `ColumnChart`

2020-11-15 21:23 UTC, dosandk requested changes
необходимо дать ответы на вопросы и внести изменения согласно комментариям

2020-11-16 12:58 UTC, chex0v commented on 05-dom-document-loading/1-notification/index.js
> +  static createElementFromString(string) {
@dosandk вынес в отдельную функцию. Static её сделал, т.е. this мне не нужен, но решил вынести её вообще в отдельную функцию.

2020-11-16 13:00 UTC, chex0v commented on 05-dom-document-loading/1-notification/index.js
> +    NotificationMessage._timer = setTimeout(
Хотел показать _, что свойство не нужно менять извне. Сделал через #, но оставил _, типа использую внутри, менять не надо. 
Статическое, т.к. 1 нотификейшен на странице и 1 таймер для него же одного.

2020-11-16 13:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-16 14:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-16 14:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-16 14:52 UTC, chex0v reviewed
@dosandk

> а почему бы не объединить эти две функции сортировки в одну? Ведь по факту они делают одно и тоже просто с разными типами данных... А проверку в switch...case как раз будет удобно орнанизовать по типу данных...

Сделал, мне просто сложно было в 1 функции учесть все параметры
Сейчас попытался


> В чем разница межу firstChild и firstElementChild?

На сколько понял firstChild возвращает ссылку на первый текстовый блок, элемент или комментарий
А firstElementChild возвращает ссылку именно на первый элемент, игнорируя комментарий и текст 
Логичнее конечно пользоваться firstElementChild в наших случаях)

2020-11-16 14:52 UTC, chex0v commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +      <div
@dosandk вынес)

2020-11-16 14:57 UTC, chex0v commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  static createElementFromString(string) {
Вынес его в функцию

Статический т.е. не нужен this, но относится как бы к элементу, но просто куда его ещё положить, вот вынес в функцию просто

2020-11-16 14:57 UTC, chex0v commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    return div.firstChild;
На сколько понял firstChild возвращает ссылку на первый текстовый блок, элемент или комментарий
А firstElementChild возвращает ссылку именно на первый элемент, игнорируя комментарий и текст 
Логичнее конечно пользоваться firstElementChild в наших случаях)

2020-11-16 15:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-17 09:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-17 11:44 UTC, dosandk approved these changes
good 👍

2020-11-17 11:44 UTC, merged